/**
 * Name: Michael Durkan 
 * ID: 17378383
 * File: Main class
 * Purpose: Run the simulation event loop, creating objects for di into the satellite
 */
package edu.curtin.mars;

import java.io.*;
import java.util.logging.Logger;
import java.util.logging.Level;
import edu.curtin.mars.controller.MarsSciSat;
import edu.curtin.mars.model.factory.ProbeFactory;
import edu.curtin.mars.observer.StatusLogger;
import edu.curtin.mars.observer.HistoryLogger;

public class Main
{
    private static final Logger logger = 
        Logger.getLogger(Main.class.getName());
    public static void main(String[] args)
    {
        // Create all the objects for dependency Injection into satellite
        CommsGenerator inp = new CommsGenerator();
        try (PrintWriter writer = new PrintWriter("diagnostics.txt"))
        {
            ProbeFactory factory = new ProbeFactory();
            StatusLogger status = new StatusLogger(writer);
            HistoryLogger history = new HistoryLogger();
            
            // Dependency Injection in to satellite
            MarsSciSat sat = new MarsSciSat(factory, status, history);
            
            // Enter the event loop
            while(System.in.available() == 0)
            {
                System.out.println("---");
                String msg = inp.nextMessage();
                logger.fine(() -> "Messaged generated by CommsGenerator");

                while(msg != null)
                {
                    // Read all the tasks from CommsGenerator for current sol
                    System.out.println(msg);
                    sat.parseMsg(msg);
                    msg = inp.nextMessage();
                    logger.fine(() -> "Messaged generated by CommsGenerator");
                }
                logger.info(() -> "Daily actions sent to satellite. Running simulation for sol");

                // Run the operations for one sol through satellite
                sat.run();
                
                // Wait 1 second
                try
                {
                    Thread.sleep(1000);
                }
                catch(InterruptedException e)
                {
                    logger.log(Level.SEVERE, "Simulation interrupted. Closing application", e);
                    throw new AssertionError(e);
                }
            }
        }
        catch(IOException e)
        {
            System.out.println("Error reading user input");
            logger.log(Level.SEVERE, "Error reading/writing diagnostics. Closing Application", e);
        }
    }
}